Setup fixes
slytomcat/yandex-disk-indicator pull request #216
Opened 2020-01-11 15:42 UTC by s3r6

2020-01-13 08:07 UTC, slytomcat requested changes

2020-01-13 08:07 UTC, slytomcat commented on ya-setup
> +      showAuthDialog
А зачем повторый вызов авторизации через рекурсию делать?  В цикле что-ли нельзя?

2020-01-13 08:07 UTC, slytomcat commented on ya-setup
> +      zenity --notification --text "Yandex disk client authorization success"
Посмотрите там локализация прикручена - либо надо использовать существующие фразы (переведенные уже) либо надо добавлять новое сообщение во се файлы и надо будет искать людей которые переведут.

2020-01-13 08:09 UTC, slytomcat reviewed
А переводы через что делали?

2020-01-13 14:14 UTC, s3r6 commented on ya-setup
> +      showAuthDialog
В цикле - `while $notAuthorized`? Используя функцию не нужно заводить переменную и повторный вызов более читабельный.

2020-01-13 14:17 UTC, s3r6 commented
Через Google translate

2020-01-13 23:33 UTC, slytomcat commented on ya-setup
> +      showAuthDialog
Завести функцию и заваливать стек рекурсивными ее вызовами это конечно экономнее чем завести одну переменную для одного (не вложенного) простого цикла. :) 

Извините, но я в душе максималист-оптимизатор и рекурсия вместо цикла - для мня - стрельба из пушки по воробьям.

Рекурсия бывает нужна - не спорю. Но не тут.

Где там нужна проверка вложенности каких циклов, и чем это вредит читабельности - мне тоже не понять...

2025-04-25 22:09 UTC, closed without merging

2025-04-25 22:09 UTC, slytomcat commented
Что-то никакой активности автора, закрыто.